Swap groups between screens
qtile/qtile pull request #2381
Opened 2021-04-13 00:25 UTC by kovasap

Continuing work for https://github.com/qtile/qtile/pull/1704.

2021-04-13 00:27 UTC, kovasap commented
At this point I'm still blocked on understanding the tests, and don't have bandwidth to work on it too much now.  I may pick it up later, or if someone else wants to see this merged I'm happy to take their guidance to finish up this PR.

2021-04-13 17:08 UTC, tych0 commented
The git history for this is kind of a mess, and I suspect it will prevent others from picking it up directly. Any chance you can clean that up?

2021-04-13 17:15 UTC, kovasap commented
Yeah good point.  I guess that would involve removing commits from the branch via rebasing?

2024-09-14 22:12 UTC, kovasap commented
I'd like to finally merge this.  @ramnes you mentioned in the original PR that you're interested in this feature (https://github.com/qtile/qtile/pull/1704#issuecomment-622625967).  I'm still not sure how to fix up the tests,  could you help or point me to some docs?

2024-09-14 23:49 UTC, ramnes commented
What is it that you need help with more precisely? FYI I'm not really involved in Qtile these days, alas.

2024-09-15 00:57 UTC, kovasap commented
Ah, I'm just a bit lost trying to make sure my tests are sufficient and
will pass.

On Sat, Sep 14, 2024, 4:49 PM Guillaume Gelin ***@***.***>
wrote:

> What is it that you need help with more precisely? FYI I'm not really
> involved in Qtile these days, alas.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/qtile/qtile/pull/2381#issuecomment-2351226209>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACC3NAWRA3L3B54RLVOZCQDZWTDQDAVCNFSM6AAAAABOHGOYMWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGNJRGIZDMMRQHE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-09-15 08:10 UTC, elParaguayo commented
I'll take a look later.

2024-10-15 18:18 UTC, kovasap commented
Gentle ping on this

2024-10-17 12:44 UTC, elParaguayo commented
I'm not convinced by this one. Seems like some code that could be kept in qtile-examples rather than being core functionality.

Also, what's the behaviour when you've got more than 2 screens. Are all groups being changed in that scenario?

2024-10-17 16:58 UTC, ramnes commented
Seems to be quite a popular thing that people implement in their config: https://github.com/search?q=qtile+AND+%28%22def+switch_screen%22+OR+%22def+swap_screen%22%29+language%3APython&type=code&l=Python

2024-10-17 17:11 UTC, elParaguayo commented
Great. Then we should include it.

2024-10-17 22:44 UTC, kovasap commented
I fixed a merge conflict but am still not sure how to proceed with the tests.

2024-10-19 07:22 UTC, elParaguayo requested changes
Thanks for this.

The commit history is also a bit of a mess. Once you've updated for my changes, can you rebase and squash the commit history to a single commit.

2024-10-19 07:22 UTC, elParaguayo commented on test/test_manager.py
> +multi_screen_manager_config = pytest.mark.parametrize("qtile", [MultiScreenManagerConfig], indirect=True)
```suggestion
manager_config = pytest.mark.parametrize("manager", [ManagerConfig], indirect=True)
multi_screen_manager_config = pytest.mark.parametrize("manager", [MultiScreenManagerConfig], indirect=True)
```
This is the cause of all the test failures. The first argument is the name of the fixture that you're parametrizing so it has to be `manager` here.

2024-10-19 07:22 UTC, elParaguayo commented on libqtile/core/manager.py
> +            self.cmd_next_screen()
```suggestion
            self.next_screen()
```
The `cmd_` prefix is deprecated.

Also, this changes the actual screen that's focused. Do you need to do that?

2024-10-19 07:22 UTC, elParaguayo commented on test/test_manager.py
> +    self = qtile
```suggestion
def test_swap_screens(manager):
```
`manager` is a defined fixture name. It needs to be used here. Please don't use the `self` alias here, that's inconsistenc across tests so those references need to be changed back to `manager`.

2024-10-19 07:22 UTC, elParaguayo commented on test/test_manager.py
> +    print(self.screens[0].__dict__)
```suggestion

```
Delete debugging statements.

2024-10-19 07:22 UTC, elParaguayo commented on test/test_manager.py
> +def test_swap_screens(qtile):
Is this exactly the same test?!

2024-10-19 07:22 UTC, elParaguayo commented on libqtile/core/manager.py
> +        """Switch groups between active screens"""
```suggestion
        """Rotate groups between active screens"""
```

2024-10-20 00:20 UTC, kovasap commented
Thanks for the notes!  I actually attempted to do that squashing earlier at the suggestion of tych0, but failed.  Is there a particular git command you have in mind to do this?  I also know that for some github repos when a pull request is merged there is an option to do an automatic squash.

2024-10-30 23:38 UTC, ervinpopescu commented
@kovasap Probably something along the lines of:
- https://docs.qtile.org/en/latest/manual/howto/git.html#i-was-told-to-rebase-my-work
- https://docs.qtile.org/en/latest/manual/howto/git.html#i-was-told-to-squash-some-commits

2025-02-28 05:33 UTC, kovasap commented
Ok, I tried the rebase method multiple times, but it seems like this branch just has more commits in it now :cry: , and the new commits i created don't look like my net changes.  Any ideas of another way I could accomplish this?

2025-02-28 05:53 UTC, closed without merging

2025-02-28 05:53 UTC, kovasap commented
I created https://github.com/qtile/qtile/pull/5195 as the successor to this with a cleaned up log.