Multilanguage keybindings support
qtile/qtile pull request #2990
Opened 2021-11-06 22:51 UTC by dydyamotya

I'm from Russia, so I needed keybindings on two key layouts. Cause I'm trying to use Wayland, I've written code for Wayland. Look, pls, if it satisfy your requirements. I think these should work for X11 also. If so, I can do this work.

2021-11-09 18:30 UTC, m-col requested changes
Nice, this is looking great so thank you for the contribution! I've added some review comments inline but overall it's looking really good.

2021-11-09 18:30 UTC, m-col commented on libqtile/backend/wayland/core.py
> +        self.multilang_mapping = MultilanguageMapping()
Please could you rename this `self._multilang_mapping` as it's only used by this class.

2021-11-09 18:30 UTC, m-col commented on libqtile/backend/wayland/core.py
> +            return (keysym, )
```suggestion
self.mapping.get(keysym, (keysym, ))
```

2021-11-09 18:30 UTC, m-col commented on libqtile/backend/wayland/core.py
> +    def __init__(self):
Please could you move this class to `keyboard.py`

2021-11-09 18:30 UTC, m-col commented on libqtile/backend/wayland/core.py
>      def ungrab_key(self, key: Union[config.Key, config.KeyChord]) -> Tuple[int, int]:
Please update the return type annotation here to reflect the multiple keysyms that could be returned. Same above with `grab_key`

2021-11-10 19:11 UTC, dydyamotya commented
I've changed everything as you suggested.
Have looked also on X11 grab_key implementation, don't know if I'd like to implement it (If someone needs it on X11). Only if you insist :D
Also it should be noted, that my implementation works if XKBCOMMON_DEFAULT variables defined before qtile launching.

There was a discussion about shortcuts. Is it possible to link it here? Or link this PR to it? Sorry, I'm noob at these things.

2022-04-27 20:34 UTC, ohadeytan commented
Any news about this? I'm using a Hebrew layout. Currently I'm using [this](https://github.com/qtile/qtile/discussions/2453#discussioncomment-1555818) as a workaround.

2022-05-01 12:56 UTC, m-col reviewed
Hey, sorry for forgetting about this. I've rebased and updated it all for you so you don't have to.

I also added another change to convert the style from a class to a function, because we don't need to keep any state around from this code so we can save some space by only getting the mappings as required (i.e. upon key grab).

Overall this looks good but unfortunately I can't test it as I don't have different keyboard layouts. Is that what is required to test it? @ohadeytan would you be willing to test it out too?

2022-05-01 21:25 UTC, ohadeytan commented
Hi @m-col, thanks for taking care of that. I tried that out and it didn't work for me, but I'm using X11, so it shouldn't work, isn't it? If it should, I will try to look into it more, maybe I missed some needed configuration.

2022-05-01 21:26 UTC, m-col commented
No I'm afraid this applies to Wayland only, sorry

2022-05-01 21:36 UTC, m-col approved these changes

2022-10-29 10:42 UTC, m-col commented
No reply on the related issue https://github.com/qtile/qtile/issues/2631, so happy to merge it as is. I've rebased it again and I'll enable it to auto-merge. Thanks for the submission! (and sorry for taking almost a year to merge it!)

2023-05-27 16:01 UTC, closed without merging

2023-12-12 06:26 UTC, Freemason-12 commented
Hey, why is this not merged? It seems like there's no issue with this PR.