refactor(libqtile): rename border(width) to border_{color,width}
qtile/qtile pull request #3530
Opened 2022-04-27 11:15 UTC by ayntgl

Closes #2825

2022-04-27 12:01 UTC, m-col commented
This is fantastic, migration and all, thank you for this!

My first thought is does this cover every single instance of `borderwidth` and `bordercolor`? A grep would be helpful for catching all of them, e.g. `backend/wayland/window.py` also uses these.

I'm also wondering how disruptive this might be. While some people hopefuly use `qtile migrate`, some don't and may get problems. I wonder how doable a phased deprecation might be, e.g. by using a keyword argument to any `Configurable` class options that catch the old versions and log a deprecation notice, and maybe keeping old versions in any `cmd_` signatures to do the same. Maybe that's overkill/unnecessary? What do you think @elParaguayo?

Lastly, please could you add a note to the changelog under the config breakage section

2022-04-27 12:21 UTC, elParaguayo commented
Nice!

My personal feeling on `migrate` scripts is that I don't particularly like them. I'm all in favour of trying to prevent breakages for users but:
- I'm sceptical as to how many users actually use the script
- I have reservations about how effective our scripts are (i.e. do we actually cover all ways a change may be required?)
- Depending on the change, the tests can be complicated to write which is frustrating given the above two points
- It looks like `bowler` is not supported past python 3.8 so may be incompatible with some users' configs.

For those reasons, I prefer the phased deprecation as per @m-col 's post above. We've got examples of this already elsewhere in the codebase.

2022-04-27 13:26 UTC, m-col commented
> EDIT: I also appreciate that my comment in the issue that this closes (https://github.com/qtile/qtile/issues/2825) said we needed a migrate script. My views have evolved since then...!

Ha, nice.

> It looks like bowler is not supported past python 3.8 so may be incompatible with some users' configs.

To be precise, bowler is no longer adding language features introduced after 3.8's walrus operator. It does work on more recent python versions and will probably continue to work for quite some time, but won't consider e.g. the newer `match` syntax. But yes, fair point. Agreed - phased deprecation would be good.

2022-04-27 14:58 UTC, elParaguayo commented
> Thank you for the feedback, @m-col @elParaguayo! Do you mind if you can point me where exactly example of phased deprecation is in the codebase?

Here's an example where we moved from a positional argument to a new parameter in `defaults`:
https://github.com/qtile/qtile/blob/b7b458073941264b2f5a84c0b49f4ed316679a9b/libqtile/widget/launchbar.py#L88-L103

2022-04-27 14:59 UTC, elParaguayo commented
> > It looks like bowler is not supported past python 3.8 so may be incompatible with some users' configs.
> 
> To be precise, bowler is no longer adding language features introduced after 3.8's walrus operator. It does work on more recent python versions and will probably continue to work for quite some time, but won't consider e.g. the newer `match` syntax. But yes, fair point. Agreed - phased deprecation would be good.

Yes - that's fair. It's not that the code doesn't work on later versions but that they won't/can't update the grammar parsing for new features.

2022-04-28 09:52 UTC, elParaguayo commented on libqtile/popup.py
> +            logger.warning(
Make sure `logger` is imported:
``` python
from libqtile.log_utils import logger
```

2022-04-28 09:54 UTC, elParaguayo commented on libqtile/widget/groupbox.py
> +            logger.warning(
Make sure `logger` is imported:
``` python
from libqtile.log_utils import logger
```
You may need to add this to the other files you changed.

2022-04-28 15:28 UTC, elParaguayo commented on libqtile/widget/groupbox.py
> +from libqtile.log_utils import logger
```suggestion
from libqtile.log_utils import logger
from libqtile.widget import base
```

2022-04-28 18:14 UTC, elParaguayo commented
OK - I've just tried this patch and there are a few bugs. I'll post some comments later.

2022-04-28 18:56 UTC, elParaguayo requested changes

2022-04-28 18:56 UTC, elParaguayo commented on libqtile/popup.py
> +            )
```suggestion
            logger.warning(
                'The "border" argument is obsolete and deprecated. '
                'As a substitute, you should use "border_color" argument instead.'
            )
```
The old `,` at the end of the first line meant you were passing two arguments to `logger.warning` when actually it should be a single string.

Also "may" -> "should".

This should be updated for the other messages.

2022-04-28 18:56 UTC, elParaguayo commented on libqtile/popup.py
> +            )
We should do tests too to check that the log messages are triggered when using deprecated configs.

An example is here:
https://github.com/qtile/qtile/blob/d827edd7b04c2fa95827c33aad3146794dfc39b2/test/widgets/test_launchbar.py#L31-L38

I don't think you'll need the monkeypatching, just initialise the widget with the deprecated parameters and check `caplog.records` for the messages.

I can help if you get stuck with these.

2022-04-28 18:56 UTC, elParaguayo commented on libqtile/scripts/migrate.py
> +    borderwidth_to_border_width,
If we're adding migrate scripts, we should test them.

Have a look at https://github.com/qtile/qtile/blob/master/test/test_migrate.py for examples.

2022-04-28 18:56 UTC, elParaguayo commented on CHANGELOG
> +        - To maintain consistency with other widgets, all of the instances of `border` parameter are renamed to `border_color` and `borderwidth` parameter to `border_width`. To easily to replace the
```suggestion
        - To maintain consistency with other widgets, all of the instances of `border`
          parameter are renamed to `border_color` and `borderwidth` parameter to
          `border_width`. To easily to replace the deprecated parameter names, 
          `qtile migrate` may be ran to replace instances of both of these parameters.
```

Splitting up long line.

2022-08-18 08:20 UTC, closed without merging