Fix margin list for xmonad layouts
qtile/qtile pull request #3750
Opened 2022-08-08 18:30 UTC by ylpoonlg

Add support for margin list for xmonad layouts as previously ignored in [#2041](https://github.com/qtile/qtile/pull/2041).
The middle margin is calculated as the maximum of the left and right (or top and bottom) margin so that it is not double counted.
I'm not sure if this should be the expected behavior but I think it makes the most sense to make it the union of two adjacent margins.

2022-08-08 18:43 UTC, elParaguayo commented
According to https://github.com/qtile/qtile/issues/3337, there is no double counting of margins in the xmonad layouts.

I'll look at your code properly later on but I've started the tests in the meantime.

2022-08-08 18:44 UTC, elParaguayo commented
Re double counting: if a user sets a margin of `5`, I would not expect to have a gap of `10` between windows.

2022-08-08 18:52 UTC, ylpoonlg commented
Sorry for the unclear context, but what I mean is that the xmonad layouts were ignored because it didn't have a strategy to combine the left and right margin into one. This PR will not break any configs, it will still work the same way when given an integer.
Example: if margin = [10, 20, 30, 40], the middle margin will be 40 (max of 20 and 40), and the horizontal margins on the secondary pane will be 30 (max of 10 and 30).

2022-08-12 06:12 UTC, elParaguayo requested changes

2022-08-12 06:12 UTC, elParaguayo commented on libqtile/layout/xmonad.py
> +
```suggestion
            # margin list
            if self.align == self._left:
                margin = [
                    margin[0],
                    margin[1],
                    margin[2],
                    max(margin[1], margin[3]),
                ]
            else:
                margin = [
                    margin[0],
                    max(margin[1], margin[3]),
                    margin[2],
                    margin[3],
                ]

```

2022-08-12 06:12 UTC, elParaguayo commented on libqtile/layout/xmonad.py
> +                margin=margin_left if self.align == self._left else margin_right,
```suggestion
                margin=margin,
```

2022-08-12 06:12 UTC, elParaguayo commented on libqtile/layout/xmonad.py
> +
```suggestion

            # margin list
            if self.align == self._left:
                margin = [
                    margin[0],
                    2 * self.border_width,
                    margin[2] + 2 * self.border_width,
                    margin[3],
                ]
            else:
                margin = [
                    margin[0],
                    margin[1],
                    margin[2] + 2 * self.border_width,
                    2 * self.border_width,
                ]

```

2022-08-12 06:12 UTC, elParaguayo commented on libqtile/layout/xmonad.py
> +                margin=margin_left if self.align == self._left else margin_right,
```suggestion
                margin=margin,
```

2022-08-12 06:12 UTC, elParaguayo commented on libqtile/layout/xmonad.py
> +
```suggestion
            # margin list
            if self.align == self._up:
                margin = [
                    max(margin[0], margin[2]),
                    margin[1],
                    margin[2],
                    margin[3],
                ]
            else:
                margin = [
                    margin[0],
                    margin[1],
                    max(margin[0], margin[2]),
                    margin[3],
                ]

```

2022-08-12 06:12 UTC, elParaguayo commented on libqtile/layout/xmonad.py
> +
```suggestion
            # margin list
            if self.align == self._up:
                margin = [
                    margin[0],
                    margin[1] + 2 * self.border_width,
                    2 * self.border_width,
                    margin[3],
                ]
            else:
                margin = [
                    2 * self.border_width,
                    margin[1] + 2 * self.border_width,
                    margin[2],
                    margin[3],
                ]

```

2022-08-12 06:12 UTC, elParaguayo commented on libqtile/layout/xmonad.py
> +                margin=margin_up if self.align == self._up else margin_down,
```suggestion
                margin=margin,
```

2022-08-12 06:13 UTC, elParaguayo commented
I've made some suggestions which would remove some unnecessary calculations.

I haven't tried this code yet though but will run the rest suite to see if the current tests still pass with your changes.

2022-10-16 14:40 UTC, elParaguayo commented
@ylpoonlg One question for you on this: if you've changed the margin calculations here why aren't the tests (`test_wide_margins` and `test_tall_margins`) now failing? Is this because they only open 2 windows?

2022-10-17 12:12 UTC, elParaguayo commented
OK - are you able to add a test for this or do you need me to do it?

2022-10-17 12:19 UTC, ylpoonlg commented
I think I should be able to do it, thanks

2022-10-19 15:24 UTC, elParaguayo commented
Ignore the failed test. That's unrelated to your test.

Could you just add some comments to your test to explain why the dimensions/positions are equal to the numbers you're checking.

2022-10-21 20:27 UTC, ylpoonlg commented
I have added some comments for one of the cases, not sure if this is enough to make it more understandable. There are too many different cases for the main pane and client panes.

2022-10-24 06:21 UTC, elParaguayo reviewed
Thanks for updating the test.

I'm still a bit confused by the logic so have added some questions for you.

2022-10-24 06:21 UTC, elParaguayo commented on test/layouts/test_xmonad.py
> +    assert_dimensions(manager, 404, 300, 388, 292)
`two` and `three` have different heights. That doesn't seem right. Is that the issue you were trying to fix?

2022-10-24 06:21 UTC, elParaguayo commented on test/layouts/test_xmonad.py
> +    assert_dimensions(manager, 408, 2, 384, 288)
`two` and `three` are still different heights (but are closer now). Is this a rounding issue?

2022-10-24 06:21 UTC, elParaguayo commented on test/layouts/test_xmonad.py
> +    # y = screen_height / 2
Shouldn't there be a an adjustment for the margin here too? Or is the whole margin applied to the window above it?

(Thinking out loud here!) I guess you can't distribute the layout evenly between windows.

2022-10-24 06:21 UTC, elParaguayo commented on test/layouts/test_xmonad.py
> +    # y = screen_height * 0.5 + max(margin[0], margin[2])
Isn't this too big? Top window finishes at y=296, you're now at y=306.

2022-10-24 08:50 UTC, ylpoonlg commented
Sorry, I know it is quite confusing. I actually didn't change how it handles combining the margins. I have just changed the values of the margins. If you take a look at the original source code of the layout, you can see how the dimensions were calculated.

I've put together a simple diagram for a test case:

![qtile_xmonad_layout](https://user-images.githubusercontent.com/56300571/197485812-d66396e6-6533-472b-abee-a290f5e4337c.png)

2023-12-10 08:06 UTC, closed without merging