doc: Improvement documentation for Match class
qtile/qtile pull request #4144
Opened 2023-01-31 18:03 UTC by jrwrigh

Stemming from conversation in #4134

Side note: the line "It can match by title, wm_class, role, wm_type, wm_instance_class or net_wm_pid." appears in the [online documentation](https://docs.qtile.org/en/stable/manual/config/groups.html#match), but not in the docstring for the method. Not sure why there's a disconnect between the docs and the source code.

2023-02-06 17:42 UTC, jwijenbergh commented
It's different in the docs because your link is the latest release. See https://docs.qtile.org/en/latest/manual/config/groups.html#match for git master. See the following blame 30bcce2d890b5559e33c992a9648588c709c8d25

2023-04-24 18:50 UTC, elParaguayo commented
So can we close this?

2023-04-25 08:57 UTC, elParaguayo commented
Sorry. Misunderstood the conversation in this thread.

Happy to merge but I'm not sure why there's a test failure here. It seems unrelated to your change.

Could you rebase this PR onto the current master and force push it so we can run the tests again. Assuming they do, I'll get this merged.

2023-04-25 09:12 UTC, jwijenbergh requested changes

2023-04-25 09:13 UTC, jwijenbergh commented on libqtile/config.py
> +    wm_instance_class or net_wm_pid.
This comment was here for a few months but I forgot to submit the review, oops!

2023-04-25 13:46 UTC, jrwrigh commented on libqtile/config.py
> +    wm_instance_class or net_wm_pid.
haha. No worries.

2023-04-25 15:44 UTC, jrwrigh commented
Looks like the errors in CI are `Invocation Errors`. I have no idea what that's supposed to mean, but I'm guessing it's probably not something to do with the PR itself? Maybe something to do with it being a PR from a fork?

2023-04-25 15:53 UTC, elParaguayo commented
> Looks like the errors in CI are `Invocation Errors`. I have no idea what that's supposed to mean, but I'm guessing it's probably not something to do with the PR itself? Maybe something to do with it being a PR from a fork?

Nope. They're your errors!

```
  libqtile/config.py:824:88: BLK100 Black would make changes.
  libqtile/config.py:824:88: W291 trailing whitespace
  libqtile/config.py:825:76: W291 trailing whitespace
```
The first error is the same as the second. So you just need to remove the whitespace at the end of lines 824 and 825.

2023-04-25 15:56 UTC, jrwrigh commented
Ah, I'm just blind. Odd that an "Invocation Error" would return when it's just a failure to have the meet the formatter.

2023-04-26 11:09 UTC, jwijenbergh commented on libqtile/config.py
> +        by Qtile itself (ie. not X11 or Wayland).
Yep indeed, you can just make it less specific. E.g. "this id is unique for each window"

2023-04-27 15:45 UTC, jrwrigh commented on libqtile/config.py
> +        by Qtile itself (ie. not X11 or Wayland).
Gotcha. I guess I found the Wayland implementation and assumed it applied to both.

2023-04-27 21:44 UTC, jwijenbergh approved these changes

2023-04-28 19:20 UTC, elParaguayo commented
The test failure is unrelated to your PR. Looks like an update to `coverage` has broken something. Have posted an issue on their site,

2023-05-01 20:55 UTC, jrwrigh commented
Done.

2023-05-01 21:48 UTC, merged