Fix extra client_mouse_enter events
qtile/qtile pull request #4537
Opened 2023-10-23 16:33 UTC by QBobWatson

The Wayland core was emitting client_mouse_enter event on every mouse motion over a non-focused client.

2023-10-23 22:39 UTC, jwijenbergh requested changes
Thanks for this! I would prefer just having this code moved above the if/else check https://github.com/qtile/qtile/blob/2347e18663fff2c2160272591d0a8d1838a957f8/libqtile/backend/wayland/core.py#L988-L992

2023-10-24 13:28 UTC, QBobWatson commented
Here you go.  I think it's more readable like this.

2023-10-24 21:11 UTC, m-col approved these changes
Awesome thanks! I really got test more with `follow_focus_mouse = False`

2023-10-24 21:19 UTC, jwijenbergh approved these changes
perfect, so clean now!

2023-10-24 21:19 UTC, merged