Delete non-persistent groups when windows are moved to another group
qtile/qtile pull request #4663
Opened 2024-01-25 00:43 UTC by ValdezFOmar

Fix #4654

Save a reference to the original group before removing it from the client and set it back before calling `DGroups._del(client)` so it can grab the reference and schedule it for deletion.

Check if the client has already been scheduled for deletion in order to avoid scheduling the same client multiple times and generating a `KeyError`.

2024-01-26 16:44 UTC, elParaguayo commented
Thanks for doing this. I'd really like to include a test in the PR to check it's working as intended. Are you able to add that?

2024-01-26 16:47 UTC, elParaguayo requested changes

2024-01-26 16:47 UTC, elParaguayo commented on CHANGELOG
> +      - Fix groups marked with `persist=False` not being deleted when their last window it's moved to another group.
```suggestion
      - Fix groups marked with `persist=False` not being deleted when their last window is moved to another group.
```

2024-01-27 01:23 UTC, ValdezFOmar commented
Sure, no problem, I can add a test. Where would it me more appropriate to add the test? I think under `test/backend/<backend>/test_window.py`, but I'm not sure.

2024-01-27 08:00 UTC, elParaguayo commented
I'd think `test/test_group.py`. This isn't backend specific and we're checking group functionality.

2024-01-27 09:13 UTC, elParaguayo commented
We try not to use `time.sleep` in our tests but there is a helper you can use:
```diff
diff --git a/test/test_group.py b/test/test_group.py
index aae57ecc..ff360a10 100644
--- a/test/test_group.py
+++ b/test/test_group.py
@@ -22,13 +22,13 @@
 # SOFTWARE.

 import random
-import time

 import pytest

 import libqtile.config
 from libqtile import layout
 from libqtile.confreader import Config
+from test.helpers import Retry


 class GroupConfig(Config):
@@ -115,6 +115,10 @@ class NoPersistGroupConfig(GroupConfig):

 @pytest.mark.parametrize("manager", [NoPersistGroupConfig], indirect=True)
 def test_non_persistent_groups(manager):
+    @Retry(ignore_exceptions=(AssertionError,))
+    def wait_for_removed(group_name):
+        assert group_name not in manager.c.get_groups()
+
     window_name = "no_match"
     manager.c.group["b"].toscreen()
     manager.test_window(window_name)
@@ -124,13 +128,11 @@ def test_non_persistent_groups(manager):
     manager.c.group[group_name].toscreen()
     assert manager.c.window.info()["name"] == window_name
     manager.c.window.togroup("a")
-    time.sleep(1)  # Wait for the group to be removed
-    assert window_name not in manager.c.get_groups()
+    wait_for_removed(window_name)

     window_name = "bar"
     manager.c.group["c"].toscreen()
     manager.test_window(window_name)
     assert manager.c.window.info()["name"] == window_name
     manager.c.window.togroup("a")
-    time.sleep(1)  # Wait for the group to be removed
-    assert "c" not in manager.c.get_groups()
+    wait_for_removed("c")
```

2024-01-27 14:22 UTC, elParaguayo approved these changes

2024-01-28 06:39 UTC, merged